auth:
- auth_name: default
  auth_type: signed_headers
base_image: oblv_ubuntu_18_04_proxy_nsm_api_python_3_8
build_args:
- name: arg
  required_arg: true
  type: integer
- name: arg2
  required_arg: false
  type: string
meta:
  author: Example
  author_email: example@oblivious.ai
  git: https://github.com/ObliviousAI/my-first-oblivious-app.git
  version: 0.1.0
paths:
- access: querier
  path: /rest_in
  short_description: Responds response from reqres.in via outbound call
- access: querier
  path: /hello
  short_description: Responds "Hello" and their name
- access: querier
  path: /resources
  short_description: Enclave resources
- access: querier
  path: /select_model
  short_description: Enclave model
roles:
- role_auth: default
  role_cardinality: 2
  role_description: The people who will be greeted
  role_name: querier
traffic:
  inbound:
  - name: main_io
    port: 80
    type: tcp
  outbound:
  - domain: portal.aws.com
    name: samp4
    port: 443
    type: tcp
  - domain: portal.aaaa.com
    name: samp3
    port: 443
    type: tcp
  - domain: portal.awbbaas.com
    name: samp5
    port: 345
    type: tcp
  - domain: reqres.in
    name: rest_in
    port: 443
    type: tcp
  - domain: stage-un-g20-nov22.cluster-clagiea8p62e.eu-west-1.docdb.amazonaws.com
    name: doc_db
    port: 27017
    type: tcp
