auth:
- auth_name: admin
  auth_type: signed_headers
base_image: ubuntu_18_04_proxy_python_3_8
meta:
  author: bhas
  author_email: bhaswar@bhaswar.com
  git: https://github.com/bhaswarpurohit/myfa.git
  version: 0.0.1
paths:
- access: query
  path: /rest_in
  short_description: fgewgf
roles:
- role_auth: admin
  role_cardinality: 1
  role_description: afasf
  role_name: query
traffic:
  inbound:
  - name: main
    port: 80
    type: tcp
  oubtbound: []
